enhancement: dont draw hittest when viewport animation is active
devexperts/dxcharts-lite pull request #133
Opened 2024-01-15 15:42 UTC by Keelaro1

2024-01-16 09:10 UTC, disyakidneyshot commented on src/chart/model/hit-test-canvas.model.ts
> +		this.canvasAnimation.animationIntervalIdSubject.subscribe(() => {
memory leak, no unsubsrcribe call

2024-01-17 11:23 UTC, KirillBobkov requested changes

2024-01-17 11:23 UTC, KirillBobkov commented on src/chart/animation/canvas-animation.ts
> +type AnimationsStatus = 'inProgress' | 'finished';
type AnimationsStatus = boolean

2024-01-17 11:23 UTC, KirillBobkov commented on src/chart/animation/canvas-animation.ts
> +	animationsStatusSubject = new BehaviorSubject<AnimationsStatus>('finished');
animationInProgressSubject = new BehaviorSubject<AnimationsStatus>(false);

2024-01-17 11:24 UTC, KirillBobkov commented
Please, add new profiler screenshot after new changes will be applied

2024-01-18 05:18 UTC, disyakidneyshot requested changes

2024-01-18 05:18 UTC, disyakidneyshot commented on src/chart/model/scale.model.ts
> +		);
but scale model is not a nice place to insert a `hitTestCanvasModel`, keep in mind, that we should keep our entities as loose coupled as possible
What was your different ideas, where to put it?

2024-01-19 15:21 UTC, disyakidneyshot approved these changes

2024-01-22 09:00 UTC, merged