Support chart pane visibility
devexperts/dxcharts-lite pull request #140
Opened 2024-01-23 09:30 UTC by Keelaro1

2024-01-25 07:57 UTC, KirillBobkov commented on src/chart/canvas/canvas-bounds-container.ts
> +					(resizerVisible && this.bounds[paneUUID].height > 0 ? paneResizerHeight : 0),
it is not possitble to set paneResizer height from config anymore?

2024-02-13 11:09 UTC, KirillBobkov requested changes

2024-02-15 11:07 UTC, KirillBobkov requested changes

2024-02-15 11:07 UTC, KirillBobkov commented on src/chart/components/pane/pane-manager.component.ts
> +	public paneVisibilityChangedSubject: Subject<void> = new Subject();
move to canvas bounds container? since panes order is stored there

2024-02-15 11:07 UTC, KirillBobkov commented on src/chart/components/pane/pane.component.ts
> +					bounds.height <= 0 ? this.hide() : this.show();
Looks like a circular dependency: `hide()/show() => recalculateBounds`
In this case,` bounds changed => hide()/show()`
How is it possible?

2024-02-16 12:44 UTC, KirillBobkov commented on src/chart/components/pane/pane.component.ts
> +					bounds.height <= 0 ? this.hide() : this.show();
I'm taking about responsibility principle. Who is responsible for calling hide/show? We change pane's state (hide/show) => bounds recalculated. It's good.
But why we need to change pane's state on bounds change? bounds is just a model, that calculates panes ratios based on provided panes and their order, it cannot control pane's state

2024-02-19 11:30 UTC, KirillBobkov requested changes

2024-02-19 11:30 UTC, KirillBobkov commented on src/chart/components/pane/pane-manager.component.ts
> +			for (const key in this.panes) {
looks like logic of caclulation new height ratios should be placed in `this.canvasBoundsContainer.recalculatePanesHeightRatios(); `based on pane's state

2024-02-19 11:30 UTC, KirillBobkov commented on src/chart/components/pane/pane-manager.component.ts
> +			for (const key in this.panes) {
looks like logic of caclulation new height ratios should be placed in this.canvasBoundsContainer.recalculatePanesHeightRatios(); based on pane's state

2024-03-13 14:38 UTC, disyakidneyshot approved these changes

2024-03-14 15:02 UTC, KirillBobkov approved these changes

2024-03-15 05:47 UTC, merged