fix: volumes object is always persists in dynamic objects
devexperts/dxcharts-lite pull request #44
Opened 2023-09-29 09:58 UTC by hokilpet

2023-09-29 09:58 UTC, dxCLA commented
[![CLA assistant check](https://cla.devexperts.com/pull/badge/not_signed)](https://cla.devexperts.com/devexperts/dxcharts-lite?pullRequest=44) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.devexperts.com/devexperts/dxcharts-lite?pullRequest=44) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.devexperts.com/check/devexperts/dxcharts-lite?pullRequest=44) it.</sub>

2023-10-03 05:30 UTC, disyakidneyshot requested changes

2023-10-03 05:30 UTC, disyakidneyshot commented on src/chart/components/volumes/volumes.component.ts
> +	volumesDrawer: VolumesDrawer
private

2023-10-03 05:30 UTC, disyakidneyshot commented on src/chart/components/volumes/volumes.component.ts
> +	dynamicObjectsComponent: DynamicObjectsComponent;
you can declare it via constructor in arguments using `private` keyword for example, and it will be the same but much less code

2023-10-03 05:30 UTC, disyakidneyshot commented on src/chart/components/volumes/volumes.component.ts
> +			paneId: this.config.components.volumes.showSeparately ? this.volumesModel.id : CHART_UUID,
are you sure `paneId` for separate volumes is `this.volumesModel.id`?

2023-10-04 07:52 UTC, disyakidneyshot approved these changes

2023-10-04 07:53 UTC, merged