fix!: fixed click/mousedown/mouseup events to be triggerd only on lef…
devexperts/dxcharts-lite pull request #61
Opened 2023-10-18 13:31 UTC by disyakidneyshot

…t mouse key

2023-10-19 07:14 UTC, hokilpet approved these changes

2023-10-19 08:16 UTC, DeltaZN requested changes

2023-10-19 08:16 UTC, DeltaZN commented on src/chart/inputlisteners/canvas-input-listener.component.ts
> +				(e: MouseEvent) => {
looks like repeated functionality, maybe extract it into a method ?

2023-10-20 09:44 UTC, DeltaZN approved these changes

2023-10-20 09:44 UTC, merged