Lock scale price time fix
devexperts/dxcharts-lite pull request #62
Opened 2023-10-19 13:41 UTC by alextsk

2023-10-20 07:43 UTC, DeltaZN commented
![lock-ratio](https://github.com/devexperts/dxcharts-lite/assets/44753430/9ea30653-1a84-4e88-9d7a-8b0ffc280215)
Noticed some jumps when scaling by Y

2023-10-20 07:44 UTC, DeltaZN requested changes
see comment above

2023-10-27 11:17 UTC, disyakidneyshot commented
> see comment above

@DeltaZN I can't reproduce this lag on my machine, maybe you can give us some steps to do so?

2023-10-27 11:19 UTC, disyakidneyshot approved these changes

2023-11-05 11:11 UTC, merged